### ISSUE TITLE
Readme file is jacked up

### ISSUE THREAD

**Issue by raboud** [loctran016/GenZOC#2]
Looks like you stole the readme file from someone else.

**Comment by loctran016** [comment]
No I'm not. I don't steal anything. The original template is here: https://github.com/othneildrew/Best-README-Template. It's free and MIT License. I DO include that in the acknowledge section

**Comment by raboud** [comment]
Read the actual read me file....it has nothing to do with the project.

**Comment by raboud** [comment]
Installation
Clone the frontend-template

**git clone https://github.com/cokaps016/frontend-template.git**
Install NPM packages

yarn install

**Comment by raboud** [comment]
Contact
cokaps016 - @cokaps016 - cokaps@icloud.com

Project Link: https://github.com/cokaps016/frontend-template
